In [ ]:
import pandas as pd
df1=pd.read_csv("/content/Depression_BERT.csv")
df2=pd.read_csv("/content/Depression_RoBERTa.csv")
df3=pd.read_csv("/content/Depression_BERT.csv")

In [ ]:
l1=df1['Labels']
l2=df2['Labels']
l3=df3['Labels']

In [ ]:
l1

0      Non_hope_speech
1      Non_hope_speech
2      Non_hope_speech
3      Non_hope_speech
4      Non_hope_speech
            ...
383    Non_hope_speech
384    Non_hope_speech
385    Non_hope_speech
386    Non_hope_speech
387    Non_hope_speech
Name: Labels, Length: 388, dtype: object

In [ ]:
df1

                                                  text           Labels
0                     Wow videos long They good points  Non_hope_speech
1    I know none business 75k income Is household c...  Non_hope_speech
2                                   Hope Is new Pokmon  Non_hope_speech
3    Almost every time someone depicts davidian sta...  Non_hope_speech
4                             disrespect body It YOURS  Non_hope_speech
..                                                 ...              ...
383         Great questions finally great answers well  Non_hope_speech
384                                           That man  Non_hope_speech
385  I wish people criticise would watch stop givin...  Non_hope_speech
386  I wanna hug MadonnannnI LOVE interviewso rawso...  Non_hope_speech
387                                     Shes charlatan  Non_hope_speech

[388 rows x 2 columns]

In [ ]:
l4=[]

In [ ]:
for i in range (len(l1)):
  c1=0
  c2=0
  c3=0
  if l1[i]=='not depression':
    c1+=1 
  elif l1[i]=='moderate':
    c2+=1
  else:
    c3+=1
  if l2[i]=='not depression':
    c1+=1 
  elif l2[i]=='moderate':
    c2+=1
  else:
    c3+=1
  if l3[i]=='not depression':
    c1+=1 
  elif l3[i]=='moderate':
    c2+=1
  else:
    c3+=1
  if c1>=2:
    l4.append('not depression')
  elif c2>=2:
    l4.append("moderate")
  else c3>=2:
    l4.append("severe")

In [3]:
test=pd.read_csv('/content/drive/MyDrive/ACL_sharedtask/Depression/test_data.tsv', sep="\t")
# test.columns=['text']
test

                Pid                                          text data
0        test_pid_1  Im scared : This is it. I lie to myself every ...
1        test_pid_2  New to this but just wanted to vent : I just f...
2        test_pid_3  Iâ€™m sad : Itâ€™s kinda always been an issue. I w...
3        test_pid_4  Lonely but not alone. : All of my immediately ...
4        test_pid_5  This year has been trash. : I dont know why Iâ€™...
...             ...                                                ...
3240  test_pid_3241  Feeling lonely. : Hi reddit, I havenâ€™t posted ...
3241  test_pid_3242  When would suicide be right? : So I got back f...
3242  test_pid_3243  Lowest Iâ€™ve ever been ever. : To make a long s...
3243  test_pid_3244  Does the Toxoplasma Gondii ruined my life ? (f...
3244  test_pid_3245  Getting the correct diagnosis : Currently goin...

[3245 rows x 2 columns]

In [ ]:
test['Lables']=l4

In [ ]:
test.to_csv('Final.csv')